### ISSUE TITLE
Publish FFS into Debian repository

### ISSUE THREAD

**Issue by dlecan** [dlecan/freefilesync-debian-package#4]

**Comment by dx486** [comment]
I hope you can do it soon. It is a long awaited package for **debian**. Please see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=648610).

**Comment by harmancode** [comment]
Hello @dlecan 

I noticed that you tried to package FFS for debian but your [RFP bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=648610) was closed due to inactivity.

Please take a look again at [How do I get a sponsor for my package?](https://wiki.debian.org/DebianMentorsFaq#How_do_I_get_a_sponsor_for_my_package.3F). It is required to prepare the package to be reviewed. I could not find a link to your package in that bug report. 

Could you please check [the Wiki](https://wiki.debian.org/DebianMentorsFaq#Packaging) again? I am sure you can find a DD to maintain your package once you make it ready to be reviewed and prepare a RFP according to the wiki. Please do not lose hope.

There is a [recent port of FFS](https://reviews.freebsd.org/rP410679) for FreeBSD. It might be helpful to you for packaging, maybe.

**Comment by dlecan** [comment]
I began to package FFS in 2010 and spent a long time in 2011 to try to upload FFS package into Debian repository. With the success we know :-)
Author is not really interested in publishing FFS into Debian or other repositories because of theirs multiple constraints and requirements.

I should try again, but the current package doeesn't match many upload requirements, so many work.
